# Generated by Django 2.1.5 on 2019-02-24 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20190224_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL),
        ),
    ]
