# Generated by Django 2.1.5 on 2019-02-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_questionsandanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finished',
            field=models.BooleanField(default='False'),
        ),
    ]
