# Generated by Django 2.1.5 on 2019-03-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_auto_20190225_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='chat',
            field=models.TextField(default=''),
        ),
    ]
