# Generated by Django 2.1.5 on 2019-04-06 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_ticket_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 6, 16, 4, 38, 936632, tzinfo=utc), verbose_name='expiration date'),
        ),
    ]
