# Generated by Django 2.1.5 on 2019-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_ticket_exp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='exp_date',
            field=models.DateTimeField(verbose_name='expiration date'),
        ),
    ]
