# Generated by Django 2.1.5 on 2019-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_auto_20190406_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='exp_date',
            field=models.DateField(verbose_name='expiration date'),
        ),
    ]
