# Generated by Django 2.1.5 on 2019-04-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_auto_20190406_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='exp_date',
            field=models.DateTimeField(verbose_name='expiration date'),
        ),
    ]
