# Generated by Django 2.1.5 on 2019-02-05 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='game',
            name='o_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_y_of_ticgame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='x_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_x_of_ticgame', to=settings.AUTH_USER_MODEL),
        ),
    ]
